version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: athenadb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_NAME: "athenadb"
    ports:
      - "8000:8000"

volumes:
  mysql_data:
